# Generated by Django 2.1.5 on 2019-04-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
